import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';import axios from 'axios';import './style.css';
const API=import.meta.env.VITE_API_URL||'http://localhost:5000/api';const api=axios.create({baseURL:API});
const empty={};
function App(){const [session,setSession]=useState(()=>JSON.parse(localStorage.getItem('session')||'null'));const [mode,setMode]=useState('login');const [form,setForm]=useState(empty);const [tasks,setTasks]=useState([]);const [interns,setInterns]=useState([]);const [error,setError]=useState('');const [notice,setNotice]=useState('');
 const isAdmin=session?.user?.role==='admin';const headers=()=>({headers:{Authorization:`Bearer ${session?.token}`}});const update=k=>e=>setForm(f=>({...f,[k]:e.target.value}));
 const load=async()=>{if(!session)return;try{const t=await api.get('/tasks',headers());setTasks(t.data);if(isAdmin)setInterns((await api.get('/interns',headers())).data)}catch(e){setError(e.response?.data?.message||e.message)}};
 useEffect(()=>{load()},[session]);const stats=useMemo(()=>({total:tasks.length,pending:tasks.filter(t=>t.status==='Pending').length,active:tasks.filter(t=>t.status==='In Progress').length,done:tasks.filter(t=>t.status==='Completed').length}),[tasks]);
 async function submit(e){e.preventDefault();setError('');try{const r=await api.post(mode==='login'?'/auth/login':'/auth/register',{...form,role:'admin'});localStorage.setItem('session',JSON.stringify(r.data));setSession(r.data);setForm({})}catch(e){setError(e.response?.data?.message||e.message)}}
 async function action(fn){try{setError('');await fn();setNotice('Saved successfully');setForm({});load()}catch(e){setError(e.response?.data?.message||e.message)}}
 if(!session)return <main className="auth"><div className="auth-card"><div className="brand">◆ InternFlow</div><h1>{mode==='login'?'Welcome back':'Create admin account'}</h1><p className="muted">A clear view of every intern, task, and deadline.</p><form onSubmit={submit}>{mode==='register'&&<input placeholder="Full name" value={form.name||''} onChange={update('name')} required/>}<input type="email" placeholder="Email address" value={form.email||''} onChange={update('email')} required/><input type="password" placeholder="Password" value={form.password||''} onChange={update('password')} required/><button> {mode==='login'?'Sign in':'Create account'} </button></form><button className="text-button" onClick={()=>{setMode(mode==='login'?'register':'login');setError('')}}>{mode==='login'?'Create the first admin account':'Back to sign in'}</button>{error&&<div className="error">{error}</div>}</div></main>;
 return <main><header><div><div className="brand">◆ InternFlow</div><p className="muted">{isAdmin?'Admin workspace':'Your internship workspace'}</p></div><div className="header-actions"><span className="user-pill">{session.user.name} · {session.user.role}</span><button className="secondary" onClick={()=>{localStorage.clear();setSession(null)}}>Log out</button></div></header>
 <section className="hero"><div><p className="eyebrow">OVERVIEW</p><h1>{isAdmin?'Team progress at a glance':'Your progress at a glance'}</h1><p className="muted">Stay on top of deadlines and keep work moving.</p></div></section>
 <section className="stats">{[['Total tasks',stats.total,''],['Pending',stats.pending,'pending'],['In progress',stats.active,'active'],['Completed',stats.done,'done']].map(([label,value,cl])=><div className="stat" key={label}><span>{label}</span><strong className={cl}>{value}</strong></div>)}</section>
 {error&&<div className="error">{error}</div>}{notice&&<div className="notice" onClick={()=>setNotice('')}>{notice}</div>}
 {isAdmin&&<section className="columns"><div className="panel"><h2>Onboard intern</h2><p className="muted">Create secure login credentials for a new intern.</p><form onSubmit={e=>{e.preventDefault();action(()=>api.post('/interns',form,headers()))}}><input placeholder="Intern name" value={form.name||''} onChange={update('name')} required/><input type="email" placeholder="Intern email" value={form.email||''} onChange={update('email')} required/><input placeholder="Temporary password" value={form.password||''} onChange={update('password')} required/><button>Add intern</button></form></div><div className="panel"><h2>Intern directory</h2>{interns.length?<div className="directory">{interns.map(i=><div className="directory-row" key={i._id}><div><b>{i.name}</b><small>{i.email}</small></div><button className="danger" onClick={()=>action(()=>api.delete('/interns/'+i._id,headers()))}>Remove</button></div>)}</div>:<p className="muted">No interns yet.</p>}</div></section>}
 {isAdmin&&<section className="panel"><h2>Assign a task</h2><form className="task-form" onSubmit={e=>{e.preventDefault();action(()=>api.post('/tasks',form,headers()))}}><input placeholder="Task title" value={form.title||''} onChange={update('title')} required/><input placeholder="Description" value={form.description||''} onChange={update('description')}/><select value={form.intern||''} onChange={update('intern')} required><option value="">Assign to intern…</option>{interns.map(i=><option value={i._id} key={i._id}>{i.name}</option>)}</select><input type="date" value={form.deadline||''} onChange={update('deadline')}/><button>Create task</button></form></section>}
 <section className="panel"><div className="panel-heading"><div><h2>{isAdmin?'All tasks':'My tasks'}</h2><p className="muted">{tasks.length} task{tasks.length!==1?'s':''} in your workspace</p></div></div><div className="task-list">{tasks.length?tasks.map(t=><Task key={t._id} task={t} admin={isAdmin} headers={headers} action={action}/>):<div className="empty">No tasks available yet.</div>}</div></section></main>}
function Task({task,admin,headers,action}){const [open,setOpen]=useState(false);const [f,setF]=useState({text:task.submission?.text||'',github:task.submission?.github||'',feedback:task.feedback||''});return <article className="task"><div className="task-main"><div className="task-title"><h3>{task.title}</h3><span className={'badge '+task.status.toLowerCase().replaceAll(' ','-')}>{task.status}</span></div><p>{task.description||'No description provided.'}</p><small>{admin&&task.intern?`Assigned to ${task.intern.name} · `:''}Deadline: {task.deadline?new Date(task.deadline).toLocaleDateString():'Not set'}</small></div><div className="task-actions"><select value={task.status} onChange={e=>action(()=>api.patch('/tasks/'+task._id,{status:e.target.value},headers()))}><option>Pending</option><option>In Progress</option><option>Completed</option></select><button className="secondary" onClick={()=>setOpen(!open)}>{open?'Close':'Details'}</button>{admin&&<button className="danger" onClick={()=>action(()=>api.delete('/tasks/'+task._id,headers()))}>Delete</button>}</div>{open&&<div className="details"><textarea placeholder="Submission notes" value={f.text} onChange={e=>setF({...f,text:e.target.value})}/><input placeholder="GitHub link" value={f.github} onChange={e=>setF({...f,github:e.target.value})}/>{admin&&<textarea placeholder="Feedback for intern" value={f.feedback} onChange={e=>setF({...f,feedback:e.target.value})}/>} {!admin&&<input type="file" onChange={e=>setF({...f,file:e.target.files[0]})}/>}<button onClick={()=>action(async()=>{if(admin)await api.patch('/tasks/'+task._id,{feedback:f.feedback},headers());else{const fd=new FormData();fd.append('text',f.text);fd.append('github',f.github);if(f.file)fd.append('file',f.file);await api.post('/tasks/'+task._id+'/submission',fd,{headers:{Authorization:`Bearer ${headers().headers.Authorization}`}})}})}>{admin?'Save feedback':'Submit work'}</button></div>}</article>}
createRoot(document.getElementById('root')).render(<App/>);
