require('dotenv').config({ path: require('path').join(__dirname, '../.env') });
const express=require('express'),mongoose=require('mongoose'),cors=require('cors'),bcrypt=require('bcryptjs'),jwt=require('jsonwebtoken'),multer=require('multer'),path=require('path'),fs=require('fs');
const app=express(); app.use(cors({origin:process.env.CLIENT_URL||true})); app.use(express.json());
const uploadDir = path.join('/tmp', 'internflow-uploads');
const upload=multer({dest:uploadDir});
const User=mongoose.model('User',new mongoose.Schema({name:String,email:{type:String,unique:true},password:String,role:{type:String,enum:['admin','intern'],default:'intern'}},{timestamps:true}));
const Task=mongoose.model('Task',new mongoose.Schema({title:String,description:String,deadline:Date,status:{type:String,enum:['Pending','In Progress','Completed'],default:'Pending'},intern:{type:mongoose.Schema.Types.ObjectId,ref:'User'},submission:{text:String,github:String,fileUrl:String},feedback:String},{timestamps:true}));
const token=u=>jwt.sign({id:u._id,role:u.role},process.env.JWT_SECRET,{expiresIn:'2d'});
const auth=(req,res,next)=>{try{const t=req.headers.authorization?.split(' ')[1];req.user=jwt.verify(t,process.env.JWT_SECRET);next()}catch(e){res.status(401).json({message:'Unauthorized'})}};
const admin=(req,res,next)=>req.user.role==='admin'?next():res.status(403).json({message:'Admin only'});
app.post('/api/auth/register',async(req,res)=>{try{const {name,email,password,role='admin'}=req.body;if(role!=='admin')return res.status(403).json({message:'Use admin onboarding for interns'});const u=await User.create({name,email,password:await bcrypt.hash(password,10),role});res.json({token:token(u),user:{id:u._id,name:u.name,email:u.email,role:u.role}})}catch(e){res.status(400).json({message:e.message})}});
app.post('/api/auth/login',async(req,res)=>{const u=await User.findOne({email:req.body.email});if(!u||!(await bcrypt.compare(req.body.password,u.password)))return res.status(401).json({message:'Invalid credentials'});res.json({token:token(u),user:{id:u._id,name:u.name,email:u.email,role:u.role}})});
app.get('/api/interns',auth,admin,async(req,res)=>res.json(await User.find({role:'intern'}).select('-password')));
app.post('/api/interns',auth,admin,async(req,res)=>{try{const {name,email,password}=req.body;const u=await User.create({name,email,password:await bcrypt.hash(password,10),role:'intern'});res.status(201).json(u)}catch(e){res.status(400).json({message:e.message})}});
app.delete('/api/interns/:id',auth,admin,async(req,res)=>{await User.findOneAndDelete({_id:req.params.id,role:'intern'});await Task.deleteMany({intern:req.params.id});res.json({message:'Deleted'})});
app.get('/api/tasks',auth,async(req,res)=>{const q=req.user.role==='admin'?{}:{intern:req.user.id};res.json(await Task.find(q).populate('intern','name email').sort({deadline:1}))});
app.post('/api/tasks',auth,admin,async(req,res)=>res.status(201).json(await Task.create(req.body)));
app.patch('/api/tasks/:id',auth,async(req,res)=>{const t=await Task.findById(req.params.id);if(!t)return res.sendStatus(404);if(req.user.role==='intern'&&String(t.intern)!==req.user.id)return res.sendStatus(403);Object.assign(t,req.body);res.json(await t.save())});
app.post('/api/tasks/:id/submission',auth,upload.single('file'),async(req,res)=>{const t=await Task.findById(req.params.id);if(!t||req.user.role==='intern'&&String(t.intern)!==req.user.id)return res.sendStatus(404);t.submission={text:req.body.text,github:req.body.github,fileUrl:req.file?`/uploads/${req.file.filename}`:t.submission?.fileUrl};t.status='Completed';res.json(await t.save())});
app.delete('/api/tasks/:id',auth,admin,async(req,res)=>{await Task.findByIdAndDelete(req.params.id);res.json({message:'Deleted'})});
app.get('/api/health',(req,res)=>res.json({ok:true}));
mongoose.connect(process.env.MONGO_URI).then(()=>app.listen(process.env.PORT||5000,()=>console.log('API running'))).catch(console.error);
